### ISSUE TITLE
Linking 

### ISSUE THREAD

**Issue by Codely-F** [MakeContributions/markdown-dungeon#119]
As i am create a new dungeon, i want to link two .md files, i need help link those two files

**Comment by paulsonjpaul** [comment]
Take a look into [adding hyperlinks in markdown languages](https://www.markdownguide.org/basic-syntax/#links).

Note that you need to use [relative URL](https://compugoddess.com/relative-vs-absolute-links/), so that your dungeon works perfectly across forks and the master branch itself.

**Pro Tip:**

If you get stuck at some point, please don't create separate issues for that. Kindly comment below the issue you are addressing (in this case, it is #103).

@ming-tsai, if you enable new [Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) feature in GitHub, people can ask these doubts there. Can be enabled by going to `Settings > Options > Features > Discussions`

**Comment by Codely-F** [comment]
Thanks,
Sorry for not knowing this.
